Регистрация и авторизация
Azcarot/go-musthave-diploma-tpl pull request #1
Opened 2024-02-16 18:32 UTC by Azcarot

2024-02-27 15:51 UTC, tmvrus requested changes
- у хендлеров одинаковые проблемы
- нет тестов
- контекст запроса из хендлеров не передается дальше в storage-layer

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/balance.go
> +		// var buf bytes.Buffer
коменты кода - дурной тон

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/balance.go
> +		}
вот этот косок повторяется 5 раз в проекте, хороший повод задуматься о middleware

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/balance.go
> +		}
вот этот косок повторяется 5 раз в проекте, хороший повод задуматься о middleware

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/balance.go
> +	balance := func(res http.ResponseWriter, req *http.Request) {
такое заворачивание хендлера  в ф-ю лишено всякого смысла, chi можно передавать сразу ф-ю с сигнатурой
`func(res http.ResponseWriter, req *http.Request)`

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/getorders.go
> +		if err == pgx.ErrNoRows {
errors.Is

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/regstration.go
> +		}
что бы вычитать тело запрос, буфер использовать не обязательно
```
data, err := io.ReadAll(req.Body)
```

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/order.go
> +		data, err := io.ReadAll(req.Body)
ошибка не проверяется

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/order.go
> +func Order(flag utils.Flags) http.Handler {
зачем передается флаг?

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/order.go
> +		err = storage.CreateNewOrder(storage.DB, order)
а что если между CheckIfOrderExists и CreateNewOrder кто-нибудь придет и добавит заказ с orderNumber ?

2024-02-27 15:51 UTC, tmvrus commented on internal/handlers/withdraw.go
> +		err = storage.WitdrawFromUser(storage.DB, userData, withdrawalData)
а что если межу GetUserBalance и WitdrawFromUser произойдет другое списание?

2024-02-27 15:51 UTC, tmvrus commented on internal/storage/postgressql.go
> +	if err == pgx.ErrNoRows {
errors.Is

2024-02-27 15:51 UTC, tmvrus commented on cmd/gophermart/main.go
> +	if flag.FlagDBAddr != "" {
а если конфиг для базы не передали, все равно нужно запускать сервис ?

2024-02-28 15:42 UTC, Azcarot commented on internal/handlers/regstration.go
> +		}
Переделал

2024-02-28 15:42 UTC, Azcarot commented on internal/handlers/order.go
> +func Order(flag utils.Flags) http.Handler {
Забыл убрать после смены логики

2024-02-28 15:42 UTC, Azcarot commented on internal/storage/postgressql.go
> +	if err == pgx.ErrNoRows {
Использую

2024-02-28 15:43 UTC, Azcarot commented on cmd/gophermart/main.go
> +	if flag.FlagDBAddr != "" {
Теперь конфиг обязателен

2024-02-28 15:43 UTC, Azcarot commented on internal/handlers/getorders.go
> +		if err == pgx.ErrNoRows {
Сделал

2024-02-28 15:43 UTC, Azcarot commented on internal/handlers/balance.go
> +	balance := func(res http.ResponseWriter, req *http.Request) {
Передаю напрямую

2024-02-28 15:43 UTC, Azcarot commented on internal/handlers/balance.go
> +		}
Сделал

2024-02-28 15:43 UTC, Azcarot commented on internal/handlers/balance.go
> +		}
Вынес в миддлвейр

2024-02-28 15:43 UTC, Azcarot commented on internal/handlers/balance.go
> +		// var buf bytes.Buffer
убрал

2024-02-28 16:43 UTC, Azcarot commented on internal/handlers/withdraw.go
> +		err = storage.WitdrawFromUser(storage.DB, userData, withdrawalData)
Теперь передаю логин через контекст

2024-02-28 16:43 UTC, Azcarot commented on internal/handlers/order.go
> +		err = storage.CreateNewOrder(storage.DB, order)
Теперь передаю номер заказа через контекст

2024-03-04 07:10 UTC, Azcarot commented on internal/handlers/withdraw.go
> +		err = storage.WitdrawFromUser(storage.DB, userData, withdrawalData)
Поставил мютекс

2024-03-04 07:10 UTC, Azcarot commented on internal/handlers/order.go
> +		err = storage.CreateNewOrder(storage.DB, order)
И поставил мьютекс

2024-03-04 09:02 UTC, tmvrus commented on internal/handlers/withdraw.go
> +		err = storage.WitdrawFromUser(storage.DB, userData, withdrawalData)
Это конечно выход, но представь, что у тебя больше 1 инстанса приложения, что бы держать больше нагрузку, тогда идея с мютексом не работает. А БД для этих целей давно придуман механизм транзакций.

2024-03-04 16:40 UTC, Azcarot commented on internal/handlers/withdraw.go
> +		err = storage.WitdrawFromUser(storage.DB, userData, withdrawalData)
Сделал транзакции, переделал немного взаимодействие с бд, чтобы легче было замокать и написал пока один тест на регистрацию пользователя

2024-03-06 20:05 UTC, merged