Iter3
Azcarot/go-musthave-diploma-tpl pull request #2
Opened 2024-02-28 16:54 UTC by Azcarot

Замечания по ревью

2024-03-05 11:54 UTC, tmvrus requested changes
Все еще контекст запроса(http.Request) не передается в storage-layer вместо этого создается context.Background() фаршируется данными, которые можно было просто передать через параметры ф-и. Созданный контекст передается последним параметром, в Go принято передавать контекст в самом начале сигнатуры.

Рекомендую еще раз ознакомиться с темой контекстов в третьем спринте.

2024-03-05 11:54 UTC, tmvrus commented on cmd/gophermart/main.go
> +	fmt.Fprintf(os.Stderr, "Missing required flag -d : DataBase address\n")
Этот код выполнится в любом случае, даже если адрес пердали

2024-03-05 11:54 UTC, tmvrus commented on internal/handlers/getorders.go
> +func ActualiseOrders(flag utils.Flags, quit chan struct{}) {
зачем сюда передавать quit если с ним ничего не происходит?

2024-03-05 11:54 UTC, tmvrus commented on internal/storage/balance.go
> +		tx, err := store.DB.Begin(ctx)
Эта транзакция ничего не гарантирует, поскольку еще до ее на чала может произойти списание в параллельном запросе: и проверку и списание нужно делать в одной транзакции/запросе

2024-03-05 11:54 UTC, tmvrus commented on internal/handlers/login.go
> +	result, err := storage.PgxStorage.CheckUserPassword(storage.ST, userData)
тут про контекст забыл

2024-03-05 19:47 UTC, Azcarot commented on internal/storage/balance.go
> +		tx, err := store.DB.Begin(ctx)
Сделал все внутри одной транзакции

2024-03-05 20:01 UTC, Azcarot commented on internal/handlers/getorders.go
> +func ActualiseOrders(flag utils.Flags, quit chan struct{}) {
Забыл убрать

2024-03-05 20:01 UTC, Azcarot commented on cmd/gophermart/main.go
> +	fmt.Fprintf(os.Stderr, "Missing required flag -d : DataBase address\n")
Да, забыл else, добавил

2024-03-05 20:09 UTC, Azcarot commented on internal/handlers/login.go
> +	result, err := storage.PgxStorage.CheckUserPassword(storage.ST, userData)
Я почему-то вообще в прошлой итерации забыл что из миддлвейр контекст возвращаю с логином и таймаутом. Теперь добавил контекст запроса практически везде, где он нужен в storage layer, но так как у меня в контексте только таймаут и логин, который берется миддлвейр из токена аутентификации, то случае с хендлером login токен нам не передают, поэтому по сути будет пустой контекст (или же только таймаут), его теперь передаю. Возможно много что упускаю еще.

2024-03-06 19:45 UTC, tmvrus approved these changes

2024-03-06 20:05 UTC, merged